events {}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    server {
        listen 80;

        limit_req zone=api_limit burst=20 nodelay;
        limit_req_status 429;

        location = /stub_status {
            stub_status;
            access_log off;
        }

        location = /users {
            proxy_pass http://172.18.0.11:30000/users;
        }

        location /users/ {
            proxy_pass http://172.18.0.11:30000;
        }

        location = /products {
            proxy_pass http://172.18.0.11:30001/products;
        }

        location /products/ {
            proxy_pass http://172.18.0.11:30001;
        }

        location = /orders {
            proxy_pass http://172.18.0.11:30002/orders;
        }

        location /orders/ {
            proxy_pass http://172.18.0.11:30002;
        }

        location / {
            return 404;
        }
    }
}